 

###Register

POST http://localhost:5000/api/expensesCategories  HTTP/1.1
content-type: application/json

{
   "name": "Test123",
   "description": "Test34",
   "expectedBudget": 123,
   "startDate": "06/11/2024"
}

###Get all EC
GET   http://localhost:5000/api/expensesCategories

 
###get by id

GET   http://localhost:5000/api/expensesCategories/666891c8334739cc0ca3f247

###update EC by id 

PUT   http://localhost:5000/api/expensesCategories/6675127226fee1cb20ef53d8 HTTP/1.1
content-type: application/json

{
   "name": "TestNameaa1",
   "expectedBudget": 2330199
}

###delete ID 
DELETE    http://localhost:5000/api/expensesCategories/6674670acae4d208bcdb0d9f HTTP/1.1
 